files:
  includes:
    - '\.yaml$'
  excludes:
    - '.git-ops-update(\.cache)?\.yaml$'
registries:
  docker:
    interval: 1h
    docker:
      url: https://registry-1.docker.io
  helm-nginx:
    interval: 1h
    helm:
      url: https://helm.nginx.com/stable
policies:
  semver:
    pattern: '^(?P<all>.*)$'
    extracts:
      - value: '<all>'
        semver: {}
  ubuntu:
    pattern: '^(?P<year>\d+)\.(?P<month>\d+)$'
    extracts:
      - value: '<year>'
        numeric: {}
      - value: '<month>'
        numeric: {}
