files:
  includes:
    - '\.yaml$'
  excludes:
    - '\.generated\.yaml$'
    - '\/system\/.*\.yaml$'
registries:
  my-docker-registry:
    interval: 1h
    docker:
      url: https://registry-1.docker.io
  my-helm-registry:
    interval: 1h
    helm:
      url: https://helm.nginx.com/stable
  my-git-hub-tag-registry:
    interval: 1h
    gitHubTag:
      credentials:
        username: ""
        password: ""
policies:
  my-semver-policy:
    pattern: '^v?(?P<version>.*)$'
    extracts:
      - value: '<version>'
        semver:
          pinMajor: yes
          pinMinor: yes
