files:
  includes:
    - '\.yaml$'
  excludes:
    - '\.git-ops-update(\.cache)?\.yaml$'
registries:
  my-docker-registry:
    interval: 1h
    docker:
      url: https://registry-1.docker.io
  my-helm-registry:
    interval: 1h
    helm:
      url: https://helm.nginx.com/stable
policies:
  my-semver-policy:
    pattern: '^(?P<all>.*)$'
    extracts:
      - value: '<all>'
        semver:
          pinMajor: yes
          pinMinor: yes
  my-ubuntu-policy:
    pattern: '^(?P<year>\d+)\.(?P<month>\d+)$'
    extracts:
      - value: '<year>'
        numeric:
          pin: yes
      - value: '<month>'
        numeric: {}
