files:
  includes:
    - '\.yaml$'
  excludes:
    - '\.generated\.yaml$'
    - '\/system\/.*\.yaml$'
registries:
  my-docker-registry:
    interval: 1h
    docker:
      url: https://registry-1.docker.io
  my-helm-registry:
    interval: 1h
    helm:
      url: https://helm.nginx.com/stable
policies:
  my-semver-policy:
    extracts:
      - semver:
          pinMajor: yes
          pinMinor: yes
