apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress
spec:
  chart:
    spec:
      chart: nginx-ingress
      sourceRef:
        kind: HelmRepository
        name: nginx-ingress
      version: 0.10.1 # {"$git-ops-update":"my-helm-registry:nginx-ingress:my-semver-policy"}
