definitions:
  creds: &creds
    username: user
    password: pass
files:
  includes:
  - '\.yaml$'
  excludes:
  - '\.generated\.yaml$'
registries:
  docker:
    interval: 1m
    docker:
      url: https://registry-1.docker.io
      credentials: *creds
  helm:
    interval: 1h
    helm:
      url: https://charts.helm.sh/stable
      credentials: *creds
  git-hub:
    interval: 1h
    gitHubTag:
      credentials: *creds
policies:
  lexicographic:
    pattern: '^(?P<all>.*)$'
    extracts:
    - value: '<all>'
      lexicographic:
        pin: yes
  numeric:
    pattern: '^(?P<all>.*)$'
    extracts:
    - value: '<all>'
      numeric:
        pin: yes
  semver:
    pattern: '^(?P<all>.*)$'
    extracts:
    - value: '<all>'
      semver:
        pinMajor: yes
        pinMinor: yes
        pinPatch: yes
        allowPrereleases: yes
git:
  author:
    name: name
    email: email
  gitHub:
    accessToken: access_token
