apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  labels:
    app: test
fail: fail # git-ops-update {"will":"fail1"}
spec:
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - name: test
          image: ghcr.io/airfocusio/git-ops-update-test:docker-v2-manifest-v0.0.1 # git-ops-update {"registry":"my-docker-registry","resource":"airfocusio/git-ops-update-test","policy":"my-semver-policy","prefix":"docker-v2-manifest-","format":"docker-image","action":"push"}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: test2
  labels:
    app: test2
spec:
  selector:
    matchLabels:
      app: test2
  template:
    metadata:
      labels:
        app: test2
    spec:
      containers:
        - image: ghcr.io/airfocusio/git-ops-update-test:docker-v2-manifest-v0.0.1 # git-ops-update {"registry":"my-docker-registry","resource":"airfocusio/git-ops-update-test","policy":"my-semver-policy","prefix":"docker-v2-manifest-","format":"docker-image","action":"push"}
          name: test
