name: 'Git Ops Update setup'
description: ''
inputs:
  version:
    description: 'version'
    default: 'latest'
runs:
  using: 'composite'
  steps:
    - if: inputs.version == 'latest'
      run: |
        cd /tmp
        URL=$(curl -fsSL https://api.github.com/repos/airfocusio/git-ops-update/releases/${{ inputs.version }} | jq -r '.assets[] | select(.name|test("linux_amd64\\.tar\\.gz$")) | .browser_download_url')
        curl -fsSL "$URL" | tar xz
        mv git-ops-update /usr/local/bin
        git-ops-update version
      shell: bash
    - if: inputs.version != 'latest'
      run: |
        cd /tmp
        URL=$(curl -fsSL https://api.github.com/repos/airfocusio/git-ops-update/releases/tags/${{ inputs.version }} | jq -r '.assets[] | select(.name|test("linux_amd64\\.tar\\.gz$")) | .browser_download_url')
        curl -fsSL "$URL" | tar xz
        mv git-ops-update /usr/local/bin
        git-ops-update version
      shell: bash
