name: test
on:
  push:
    branches:
    - "*"
  pull_request:
    branches:
    - main
env:
  GO111MODULE: on
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: 1.19.x
    - uses: actions/checkout@v2
    - name: Log in to ghcr.io
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - run: make test
